### PR TITLE
Squashing support

### LINKED ISSUE #22: Comment commands
It would be great if the bot could react to commands in comments.
For example:

jsDelivr mod: `@jsdelivrbot: squash commits` and all commits in that PR will get squashed into a single one

Scenario: The bot created an update PR for a project. All mods are asleep.
The developer of the project that is getting updated can comment:
Author: `@jsdelivrbot: merge this PR`

### LINKED ISSUE #34: 2 commit rule
We can create a warning when the user has more than 2 commits and then show him the correct command to squash his commits.

2 because = info.ini + update.json to allow users to use the web interface

### PR DESCRIPTION
**Pull request by megawac**
This should allow a collaborator to make a comment like `@jsdelivrbot squash and merge` in a PR issue and the bot will attempt to merge it

The following steps are used whenever a comment is made on a pr (not a diff comment)

- [x] check to see if the comment is matched by the regexp `merge_re`
- [x] Validate commentor is a collaborator
- [x] Ensure issue has more than 1 commit in it (I don't know what will happen if this isn't the case)
- [x] Create a commit message that will close the current issue (if successful) (e.g. `Add jquery; closes #4500`). Currently the commit message is based on the PR title
- [x] Execute that shell script (read the steps it follows there
- [x] Push the squashed commit and close the PR
- [x] Send a message if it fails

Some testing is still needed (the shell script works but I'm not sure if the comment checking (matching the `merge_re` regexp) works yet)

/cc @jimaek 

Fixes #22; Fixes #34

### CODE REVIEW

**Comment by jimaek** [comment]
So it auto-merges and closes the PR? I guess this means that we send the command only once everything is 100% fixed

**Comment by megawac** [comment]
Yeah its a command for when the PR is good to go besides # of commits

For example:
- https://github.com/jsdelivr/jsdelivr/pull/4614
- https://github.com/jsdelivr/jsdelivr/pull/4628

**Comment by jimaek** [comment]
Ok great, thank you

**Comment by megawac** [comment]
Finishing a couple more tests - I'll merge it a bit later

**Pull request merged**
